service: discord-notifier

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  versionFunctions: false
  tracing:
    lambda: true 

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  discord-notifier:
    handler: bin/notifier
    events:
# Sample EC2 event
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.ec2'
#            detail-type:
#              - 'EC2 Instance State-change Notification'
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.codepipeline'
#            detail-type:
#              - 'CodePipeline Action Execution State Change'
      - cloudwatchEvent:
          description: Failed Builds
          event:
            source:
              - aws.codebuild
            detail-type:
              - CodeBuild Build State Change
            detail:
              build-status:
              - FAILED
          inputTransformer:
            inputPathsMap:
              version: '$.version'
              id: '$.id'
              source: '$.source'
              account: '$.account'
              time: '$.time'
              region: '$.region'
              resources: '$.resources'
              detail-type : '$.detail-type'
              build-status: '$.detail.build-status'
              project-name: '$.detail.project-name'
              build-id: '$.detail.build-id'
              logs: '$.detail.additional-information.logs.deep-link'
            inputTemplate: '{"version": <version>, "id" : <id>, "detail-type": <detail-type>, "source": <source>, "account": <account>, "time": <time>, "region": <region>, "resources": <resources>, "detail": { "build-status": <build-status>, "project-name": <project-name>, "build-id": <build-id>, "logs-link": <logs> } }'
        
      - cloudwatchEvent:
          description: Changes to organization-formation repo
          event:
            source:
              - aws.codecommit
            detail-type:
              - CodeCommit Repository State Change
            resources:
              - arn:aws:codecommit:ap-southeast-2:731244687126:organization-formation

    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}