service: discord-notifier

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  versionFunctions: false
  tracing:
    lambda: true 

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  discord-notifier:
    handler: bin/notifier
    events:
# Sample EC2 event
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.ec2'
#            detail-type:
#              - 'EC2 Instance State-change Notification'
#      - cloudwatchEvent:
#          event:
#            source:
#              - 'aws.codepipeline'
#            detail-type:
#              - 'CodePipeline Action Execution State Change'
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codebuild'
            detail-type:
              - 'CodeBuild Build State Change'
            detail:
              build-status:
              - 'FAILED'
    environment:
      DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}